version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    rebase-strategy: "auto"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "maven"
    groups:
      maven-minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      maven-major:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "auto"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "10:30"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions-minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      actions-major:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"